version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ruwan
      - MONGO_INITDB_ROOT_PASSWORD=ruwan
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ruwan
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ruwan
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-network

volumes:
  mongo: {}

networks:
  mongo-network:
    driver: bridge